# Unique key for this project in SonarQube
sonar.projectKey=angular-docker-app
sonar.projectName=Angular Docker App
sonar.projectVersion=1.0

# Path to source code
sonar.sources=src

# Exclude dependencies and build outputs from analysis
sonar.exclusions=**/node_modules/**,**/*.spec.ts,**/dist/**,**/coverage/**

# Test inclusions and coverage location
sonar.tests=src
sonar.test.inclusions=**/*.spec.ts
sonar.typescript.lcov.reportPaths=coverage/lcov.info

# Source encoding
sonar.sourceEncoding=UTF-8